name: Create PR from new XKCP Release
on:
  repository_dispatch:
    types: [release]
jobs:
  fetch-new-xkcp-artifacts-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch git metadata for committing to runtimes
        run: git pull -f --update-shallow origin $(git branch --show-current)
      - name: Download Windows Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "StirlingLabs/XKCP"
          version: "tags/${{ github.event.client_payload.tag }}"
          file: "XKCP-win.tar.gz"
          target: "XKCP-win.tar.gz"
          token: ${{ github.token }}
      - name: Download OSX Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "StirlingLabs/XKCP"
          version: "tags/${{ github.event.client_payload.tag }}"
          file: "XKCP-osx.tar.gz"
          target: "XKCP-osx.tar.gz"
          token: ${{ github.token }}
      - name: Download Linux Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "StirlingLabs/XKCP"
          version: "tags/${{ github.event.client_payload.tag }}"
          file: "XKCP-linux.tar.gz"
          target: "XKCP-linux.tar.gz"
          token: ${{ github.token }}
      - name: Extract and commit artifacts
        run: |
          # Configure Git
          git config user.email "daemon@stirlinglabs.com"
          git config user.name "StirlingLabsDaemon"
          # Extract Files
          tar --wildcards --overwrite -xf XKCP-linux.tar.gz -C XKCP.NET/runtimes/linux-x64/native/ '*.so'
          tar --wildcards --overwrite -xf XKCP-osx.tar.gz -C XKCP.NET/runtimes/osx-x64/native/ '*.dylib'
          tar --wildcards --overwrite -xf XKCP-win.tar.gz -C XKCP.NET/runtimes/win-x64/native/ '*.dll'
          # Commit changes
          git commit -m "New version of StirlingLabs/XKCP ${{ github.event.client_payload.tag }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ github.token }}
          title: 'New version of StirlingLabs/XKCP ${{ github.event.client_payload.tag }}'
          branch: check-xkcp
          body: |
            [${{ github.event.client_payload.tag }} release of StirlingLabs/XKCP](https://github.com/StirlingLabs/XKCP/releases/tag/${{ github.event.client_payload.tag }})
          labels: |
            automated-pr
            xkcp
