name: CD
on: [push]
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: cake-build/cake-action@v1
        with:
          target: Build
      - name: Run Test
        uses: cake-build/cake-action@v1
        with:
          target: Run-Tests
      - name: Create Nuget Package
        uses: cake-build/cake-action@v1
        with:
          target: Pack   
      - name: Push Nuget Pack
        uses: cake-build/cake-action@v1
        with:
          target: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        name: XKCP.NET
        with:
          name: XKCP
          path: |
            artifacts/*.nupkg
          if-no-files-found: error       
  create-release:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download XKCP.Net
        uses: actions/download-artifact@v2
        with:
          name: XKCP.NET
          path: artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: XKCP.NET
          files: |
            artifacts/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          