name: Deployment
on:
  push:
    tags:
      - 'v*'
jobs:
  create-release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --no-build
      - name: Push NuPkg
        run: dotnet nuget push artifacts/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate --no-symbols
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: XKCP.NET
          path: |
            artifacts/*.nupkg
          if-no-files-found: error
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: XKCP.NET
          files: |
            artifacts/*.*
        env:
          GITHUB_TOKEN: ${GITHUB_TOKEN}
