name: Integration
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Fetch tag git metadata
        run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
      - uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
      - name: Build
        run: dotnet build XKCP.NET.sln -c Release
      - name: Test
        run: dotnet test XKCP.NET.sln --no-build -c Release --logger GitHubActions
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: XKCP.NET
          path: |
            artifacts/*.nupkg
            coverage
          if-no-files-found: error
# disable right now to evade comments turning into email spam
#      - name: Read and escape coverage summary
#        id: get-comment-body
#        run: |
#          body=$(cat coverage/Summary.md)
#          body="${body//'%'/'%25'}"
#          body="${body//$'\n'/'%0A'}"
#          body="${body//$'\r'/'%0D'}" 
#          echo ::set-output name=body::$body
#      - name: Create coverage commit comment
#        uses: peter-evans/commit-comment@v1
#        with:
#          body: ${{steps.get-comment-body.outputs.body}}
