name: Integration
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
      - name: Build
        run: dotnet build XKCP.NET.sln
      - name: Test
        run: dotnet test XKCP.NET.sln --no-build
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: XKCP.NET
          path: |
            artifacts/*.nupkg
          if-no-files-found: error
      - uses: romeovs/lcov-reporter-action@v0.2.21
        name: Upload Coverage 
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
