name: Integration
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --no-build
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: XKCP.NET
          path: |
            artifacts/*.nupkg
          if-no-files-found: error
